apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ deployName }}
  namespace: {{ namespace }}
  labels:
    app: {{ projectName }}-{{ deployName }}
spec: 
  capacity: 
    storage: 40Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    server: {{ nfsServer }}
    path: {{ nfsPath }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ deployName }}
  namespace: {{ namespace }}
spec: 
  accessModes:
  - ReadWriteMany
  resources: 
    requests: 
      storage: 40Gi
  selector: 
    matchLabels: 
       app: {{ projectName }}-{{ deployName }}




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ deployName }}
  namespace: {{ namespace }}
  labels:
    app: {{ projectName }}-{{ deployName }}
spec:
  replicas: {{ replicas }}
  selector: 
    matchLabels: 
      app: {{ projectName }}-{{ deployName }}
  template:
      metadata:
        labels:
          app: {{ projectName }}-{{ deployName }}
      spec:
        containers:
        - name: {{ deployName }}
          image: {{ mirror }}
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "{{ mysqlPassword }}"
          volumeMounts:
          - name: {{ deployName }}-data
            mountPath: /var/lib/mysql
          - name: {{ deployName }}-conf
            mountPath: /etc/mysql/conf.d/my.cnf
          ports:
          - name: mysql
            containerPort: {{ port }}
            #hostPort: {{ port }}
        volumes:
        - name: {{ deployName }}-conf
          configMap: 
             name: {{ deployName }}-conf
        - name: {{ deployName }}-data
          persistentVolumeClaim: 
            claimName: {{ deployName }}
            #hostPath: 
            #path: /root/nuclearpower/mysql/project/data 



---

apiVersion: v1
kind: Service
metadata:
  name: {{ deployName }}-svc
  namespace: {{ namespace }}
spec:
  ports:
  - name: mysql
    nodePort: 30036
    port: {{ port }}
    protocol: TCP
    targetPort: {{ port }}
  selector:
    app: {{ projectName }}-{{ deployName }}
  type: NodePort

